name: Update Homebrew

on:
  schedule:
    # weekdays at 00:00
    - cron: '0 0 * * 1-5'

  workflow_dispatch:
    inputs:
      newOnly:
        description: Only operate on outdated formulae
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  update_homebrew:
    name: Update Insomnia Formula
    # must be macos, linux-brew doesn't have casks
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Add "Versions" Tap
        run: brew tap homebrew/homebrew-cask-versions

      - name: Any Outdated Formulae
        id: formulae
        run: |
          set -eo pipefail
          set -x

          echo "::set-output name=outdated::false"

          if [[ "${{ github.event.inputs.newOnly }}" == 'true' ]]; then
            NEWER_ONLY_FLAG=' --newer-only '
          fi

          for cask in $(
            brew livecheck "${NEWER_ONLY_FLAG:-}" --json inso-beta \
              | jq -r '.[] | "\(.cask) \(.version.latest)"'
          ); do
            # overwrite to "true" for any iterations through this loop
            echo "::set-output name=outdated::true"

            # set outputs for latest version by cask name
            echo "::set-output name=${cask%% *}::${cask##* }"
          done

      - name: No Updates Required
        if: steps.formulae.outputs.outdated == 'false'
        run: echo "::notice ::Formulae already up to date! 🎉"

      - name: Bump 'inso-beta' Cask
        if: |
          steps.formulae.outputs.outdated == 'true' &&
          contains(steps.formulae.outputs.*, 'inso-beta')
        run: |
          latest='${{ steps.formulae.outputs.inso-beta }}'
          echo "::notice ::updating inso-beta to ${latest}"
          brew bump-cask-pr \
            --no-fork \
            --no-browse \
            '--message=Created by Github Actions in the [Kong/Insomnia repository](https://github.com/Kong/insomnia)' \
            --version="$latest" \
            inso-beta

      - name: Bump 'inso' Cask
        if: |
          steps.formulae.outputs.outdated == 'true' &&
          contains(steps.formulae.outputs.*, 'inso')
        run: |
          latest='${{ steps.formulae.outputs.inso }}'
          echo "::notice ::updating inso to ${latest}"
          brew bump-cask-pr \
            --no-fork \
            --no-browse \
            '--message=Created by Github Actions in the [Kong/Insomnia repository](https://github.com/Kong/insomnia)' \
            --version="$latest" \
            inso

      - name: Bump 'insomnia' Cask
        if: |
          steps.formulae.outputs.outdated == 'true' &&
          contains(steps.formulae.outputs.*, 'insomnia')
        run: |
          latest='${{ steps.formulae.outputs.insomnia }}'
          echo "::notice ::updating insomnia to ${latest}"
          brew bump-cask-pr \
            --no-fork \
            --no-browse \
            '--message=Created by Github Actions in the [Kong/Insomnia repository](https://github.com/Kong/insomnia)' \
            --version="$latest" \
            insomnia
